### ISSUE TITLE
Cosmetic rules for vk.com break music playback

### ISSUE THREAD

**Issue by Lichtenshtein** [SkeletalDemise/Skeletal-Blocker#1]
### Test link: 
https://vk.com/audios* <-etc

Cosmetic rules for vk.com break music playback. All songs except that are blocked by rightholders just don't show up. Here are the rules that cause the problem I suppose

##div[id*="ads"]
##div[id*="_ad"]
##div[class*="ads"]
##div[class*="ads"]

**Comment by SkeletalDemise** [comment]
The site looks like you need to make an account, and you also need to verify it with a phone number.

**Comment by Lichtenshtein** [comment]
Yes..I could give you an account for tests, but i'm afraid it'll require verification via sms because of strange geolocation. Is there a way to create an exception for the css rule? I'm using uBlock Origin.

**Comment by SkeletalDemise** [comment]
This should be fixed now.

**Comment by Lichtenshtein** [comment]
Fixed. Thank you!
